### ISSUE TITLE
Finish specification for Unified Content Blocks

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/pm#101]
- [x] Review materials and improve task descriptions in epic: #100
- [x] Incorporate weighted `Ballot`s.
  - [x] Multiple eligibilities in same layer.
  - [x] Consider PoET ticks effect on weight.
  - [x] Support multiple `Proposal`s for a single `Ballot`.
- [ ] Create SMIP.

**Comment by lrettig** [comment]
this was implemented
