### ISSUE TITLE
Genesis nonce scheme

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#104]
Under account unification, each principal account is free to implement its own nonce scheme. For genesis, we need to design and implement one standard, recommended nonce scheme that will be included in the genesis smart contracts.

See https://community.spacemesh.io/t/nonce-schemes-and-account-unification/202

Other links to read:
- https://ethresear.ch/t/account-abstraction-radically-simplified/3769/17
- https://ethresear.ch/t/using-binary-vector-clocks-to-replace-transaction-nonces/7290/1

SMIP: https://github.com/spacemeshos/SMIPS/issues/79

Related: #20

- [x] Review [forum thread](https://community.spacemesh.io/t/nonce-schemes-and-account-unification/202)
- [x] Update [tx structure doc](https://docs.google.com/document/d/1QSBsBdDvB3zc0J8jJgN5Y4iv9T5HDcD0QONsQbig5Po/edit#)
- [x] Review tx structure doc with @noamnelke and @dshulyak 
- [x] Decide how/where tx sorting happens (outside VM, as `cmax | ~noncemask`)
- [x] Decide how/where nonce checking (validity predicate) happens (inside `verify()`)
- [x] Decide how/where nonce update happens (inside VM, `NonceUpdate` template method)
- [x] Dev task breakdown (#104)

**Comment by lrettig** [comment]
Noam described this in [tx structure doc](https://docs.google.com/document/d/1QSBsBdDvB3zc0J8jJgN5Y4iv9T5HDcD0QONsQbig5Po/edit#)

**Comment by lrettig** [comment]
Finished reviewing forum thread, and updated tx structure doc. Next step: discuss with Noam and Dima, make final decisions (see checklist above), then write dev task breakdown.

**Comment by lrettig** [comment]
Discussed this with @noamnelke and @selfdual-brain today. We decided to stick with a simple "int nonces with gaps" scheme: see #150 for the straightforward proposed design and dev tasks breakdown. We'll continue to discuss more sophisticated, generalized nonce schemes for the future.

**Comment by dshulyak** [comment]
@lrettig it looks like you shared the link to this page
