### ISSUE TITLE
Overlooked/Stale TODOs in Hare Package

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#122]
https://www.notion.so/spacemesh/Overlooked-Stale-TODOs-in-Hare-Package-c0f9f70298534ff29bbb6a599690dcb7

**Comment by lrettig** [comment]
@dshulyak could you please take a look at the linked issues (in the notion doc) and see if they're still relevant in light of hare3? Thanks.

**Comment by dshulyak** [comment]
it is safe to close it
