### ISSUE TITLE
Implement: PoET ticks

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#143]
Requires: spacemeshos/pm#124

- [x] ensure that merkle tree library supports unbalanced trees https://github.com/spacemeshos/merkle-tree/pull/16
- [x] make poet aware of epoch duration https://github.com/spacemeshos/poet/pull/112
- [x] integrate new poet config into systests https://github.com/spacemeshos/go-spacemesh/pull/3396
- [x] add poet ticks to activation and include them into weight computation https://github.com/spacemeshos/go-spacemesh/pull/3399
- [x] add poet tick to block from proposals https://github.com/spacemeshos/go-spacemesh/pull/3405
- [x] ballots should not be able to vote for future blocks https://github.com/spacemeshos/go-spacemesh/pull/3447

**Comment by dshulyak** [comment]
last task blocked on a discussion with Tal

**Comment by lrettig** [comment]
Adding @noamnelke to resolve this - he's planning to discuss with @tal-m shortly
