### ISSUE TITLE
Block-level spam defense

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#144]

**Comment by selfdual-brain** [comment]
There is a class of attacks where smeshers, potentially with very small weight, use their ballots to introduce blocks that were not constructed following consensus rules. An attacker can effectively drag honest nodes into downloading overwhelming numbers of blocks (think - petabytes) which will end up being junk. Hence this will end up as a form of DoS attack, where the P2P network is clogged.

 We need to introduce a defense against such attacks.

**Comment by selfdual-brain** [comment]
Spec: https://community.spacemesh.io/t/deferred-block-fetching-a-k-a-dangling-pointers/309
