### ISSUE TITLE
Initial gas metering (genesis parameters)

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#145]
Set initial gas costing for all genesis contracts and calls.

The most straightforward approach is to fix the gas cost for a basic operation, e.g., our "simple send" analogue, on the order of magnitude of 10,000-100,000 (e.g., ETH uses 21k), and then calculate a gas cost table relative to this.

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3611
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3612

**Comment by lrettig** [comment]
@dshulyak already implemented some basic fix costs. @WilfredTA will determine whether this is sufficient for genesis.

**Comment by dshulyak** [comment]
What i set is not sufficient. Those numbers are just placeholders.

**Comment by selfdual-brain** [comment]
Agreed gas formula for Genesis is available here:
https://community.spacemesh.io/t/nonce-in-self-spawn-never-ending-battle/304/4?u=selfdual-brain

**Comment by lrettig** [comment]
Possibly useful: https://medium.com/aptoslabs/the-making-of-the-aptos-gas-schedule-508d5686a350

**Comment by lrettig** [comment]
Hopefully helpful: #210

**Comment by pigmej** [comment]
The current values are set and considered being "good enough". More info https://github.com/spacemeshos/pm/issues/145

**Comment by lrettig** [comment]
This was done in:

- https://github.com/spacemeshos/go-spacemesh/issues/3611
- https://github.com/spacemeshos/go-spacemesh/issues/4270 (initial gas table is here)
- https://github.com/spacemeshos/go-spacemesh/issues/4271

See also: https://community.spacemesh.io/t/gas-cost-for-precompiles/348

Assuming @dshulyak is happy with the current state; let us know if there's any more to be done here for genesis
