### ISSUE TITLE
POPS VRF beacon and mitigation

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#146]
Based on my understanding there are two outstanding tasks from [this forum thread](https://community.spacemesh.io/t/possible-dos-against-pops-vrf-beacon-and-mitigation/210):

- mitigation to have nodes fix an upper bound u on the weight of proposals
- ID generation nonce

@tal-m [indicates](https://spacemesh.slack.com/archives/CG91F13C7/p1642711701101500?thread_ts=1642513565.086000&cid=CG91F13C7) that neither are genesis critical and that the latter, in particular, would be nice to have for genesis.

Marking for 1.1 milestone for now

Related: https://github.com/spacemeshos/SMIPS/issues/45

**Comment by moshababo** [comment]
Closing in favor of https://github.com/spacemeshos/pm/issues/172.

**Comment by moshababo** [comment]
Closing in favor of https://github.com/spacemeshos/pm/issues/172.
