### ISSUE TITLE
Choose tool/platform to host new docs

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#147]
Candidates:
- Docusaurus: looks good, open source, designed for markdown-based docs, React-based static site generator; see https://docusaurus.io/docs#comparison-with-other-tools
- VuePress: similar to to Docsaurus, based on Vue
- Gitbook: more commercial, has its own editor + version control, etc. - we want to keep these things in Github
- Docsify: not a static site generator, dead simple, used this previously for product/testnet/protocol docs
- MkDocs: simpler than Docsaurus, no React
- [Sphinx](https://www.sphinx-doc.org/en/master/index.html): more complex to set up

CC @oriya, @yaelmhoffman, @AskalAl, @selfdual-brain

**Comment by lrettig** [comment]
Assuming we want to keep our homepage and blog separate, we should probably keep using docsify since it's dead simple, we don't need react or fancy customizability, etc. If OTOH we want to set up a single megasite, Docusaurus is probably the best choice.

**Comment by yaelmhoffman** [comment]
I've been playing around with Docusaurus to make a demo site, and I have to say that I like it a lot.

**Comment by yaelmhoffman** [comment]
While Docsify is definitely simpler, I think Docusaurus' default theme and layout looks a lot more professional.

**Comment by yaelmhoffman** [comment]
Here are some screenshots of the demo site I made using Docusaurus:

![preview2](https://user-images.githubusercontent.com/56118594/180861010-052c07c1-dd81-46f7-8836-616bd191723b.png)
![preview3](https://user-images.githubusercontent.com/56118594/180861022-062c5583-2572-4644-9d5a-4421b58dff2f.png)

**Comment by lrettig** [comment]
Let's get a placeholder site up in the next day or two at docs.spacemesh.io or spacemesh.io/docs, set up placeholders for the 12 sections specified in the [master plan](https://docs.google.com/document/d/10IfmWdSdvIKbF4m6XQbf3E-Nt_Yu6ITqd04zSj-ndqo/edit#), and begin fleshing it out. I can set this up as a new repository and give everyone access.

**Comment by lrettig** [comment]
@yaelmhoffman does this live in a repo now that I can take a look at?

**Comment by yaelmhoffman** [comment]
> @yaelmhoffman does this live in a repo now that I can take a look at?

Yes. It's still private, but I've just added you as an admin: https://github.com/spacemeshos/docs

This is all preliminary and open to change. I just wanted a visual of what I had in mind for the overall documentation structure and organization.

**Comment by lrettig** [comment]
We've decided to go with docusaurus
