### ISSUE TITLE
POPS-VRF

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#168]
Motivation:

- in order to make it costly for an adversary to grind on smesher IDs (to prevent attacks against the beacon and concentration attacks more generally), we want to make it costly to generate a new smesher ID
- we need a way to bind genesis ID to a smesher ID so that the same smesher ID cannot be used on multiple chains that do not share a common genesis

Proposed solution:

Add a step to the "smesher initialization" process by which a smesher begins smeshing:

1. generate a new keypair (arbitrary, smesher is free to choose this)
2. use this to generate the initial PoST data (which commits to genesis ID) and initial PoET challenge
3. submit PoET challenge and wait for result
4. **new step:** run a short PoW to find a nonce on this PoET output
5. include this nonce in all future VRF messages `f(x) = vrf(nonce, x)`

See [this thread](https://community.spacemesh.io/t/tortoise-beacon-based-on-bad-vrf/100/30) for more.

Note: because finding the nonce involves PoW, it's theoretically possible that, if the adversary performs enough work, they could find a single nonce that validates multiple genesis IDs. Due to the extra work involved, we don't think this is a problem.

Note: [this thread](https://community.spacemesh.io/t/possible-dos-against-pops-vrf-beacon-and-mitigation/210) and #146 refer to additional, related work to make this ID generation/nonce scheme robust against a certain class of DoS attack, but that's less important for genesis and is scheduled for a later upgrade.

**Comment by dshulyak** [comment]
> run a short PoW to find a nonce on this PoET output

i guess this will be using post library. maybe @moshababo recalls what we should use

**Comment by moshababo** [comment]
As a result of [this thread](https://community.spacemesh.io/t/tortoise-beacon-based-on-bad-vrf/100), the following feature was implemented: https://github.com/spacemeshos/SMIPS/issues/45.
It was already fully integrated, yet remained turned off (see [here](https://github.com/spacemeshos/post/blob/develop/gpu/api.go#L99)). 


[Later](https://spacemesh.slack.com/archives/CG91F13C7/p1642711701101500?thread_ts=1642513565.086000&cid=CG91F13C7), Tal mentioned it's unusable for this specific attack.

**Comment by moshababo** [comment]
Closing in favor of https://github.com/spacemeshos/pm/issues/172.

**Comment by moshababo** [comment]
Closing in favor of https://github.com/spacemeshos/pm/issues/172.
