### ISSUE TITLE
improve PoET server resilience

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/pm#174]
## Description

action items from the meeting of improving resilience of poet servers.

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3458
- [x] https://github.com/spacemeshos/poet/issues/144
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3460 node register to multiple poet servers

on the infra side, we need to put poet servers behind a API gateway for DDoS

**Comment by pigmej** [comment]
@fasmat @moshababo @countvonzero I moved it here to track multi repo and more "PM" like issues here instead of go-spacemesh.

There is also https://github.com/spacemeshos/pm/issues/173 which is related to this one.
