### ISSUE TITLE
Amortize the cost of finding a nonce for POPS-VRF

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#175]
## The task

Amortize the computation cost of finding a nonce to support the [POPS-VRF](https://github.com/spacemeshos/pm/issues/172) scheme through the cost of PoST initialization. Then apply it to the initial ATX.

## Background

https://github.com/spacemeshos/gpu-post supports the amortization via the `COMPUTE_POW` flag (which was added in addition to the `COMPUTE_LEAFS` flag, needed for the actual initialization). For more info, see [here](https://github.com/spacemeshos/SMIPS/issues/45).

## Breakdown 

https://github.com/spacemeshos/post & https://github.com/spacemeshos/go-spacemesh

* Enable the activation of the `COMPUTE_POW` flag, and use it in order to find a nonce which satisfies `H( nonce ++ VRFpk ++ PositioningATX ) < d`. 
* Create a calculation function for the difficulty threshold `d`. It should define a probability of finding one single nonce for the entire PoST initialization, meaning one for every (number of units) *  (number of labels per unit), when applied to the total range of values space in 32 bytes.
* If no successful nonce was found during the entire initialization phase, continue to compute labels for nonce-finding, PoW purposes only (`COMPUTE_LEAFS` off, `COMPUTE_POW` on), until succeeding.
* Upon finding a successful nonce
   * Add it to the initial ATX
   * Add it to the PoST metadata file
 * Verify incoming initial-ATXs' nonce to satisfy `H( nonce ++ VRFpk ++ PositioningATX ) < d`. The hash function is the work oracle function from PoST initialization, also used in PoST verification to compute a given label.

**Comment by fasmat** [comment]
When adding the nonce to the post metadata file, consider also adding the positioning atx to it (instead of string it in the DB as it's currently done).
