### ISSUE TITLE
Hare: Do we need to accept multiple Hare PreRound messages from a single node?

### ISSUE THREAD

**Issue by jonZlotnik** [spacemeshos/pm#178]
Currently both the Hare broker and the main algorithm assume that it is required to accept multiple pre-round messages from a single node. This is problematic for the reasons in the issues referencing this issue.

Is there a security concern if we decide to only accept a single message for each round type from each node?

**Comment by jonZlotnik** [comment]
- [ ] Does the current node implementation (the msg sending part) assume that it can send multiple preround messages?

**Comment by selfdual-brain** [comment]
This problem will get resolved if we apply the solution proposed here:
https://community.spacemesh.io/t/hare-equivocations-defense/329
