### ISSUE TITLE
Genesis hardcoded templates

### ISSUE THREAD

**Issue by selfdual-brain** [spacemeshos/pm#180]
Genesis version of Spacemesh will not have real SVM. Instead, a hardcoded collection of templates will be implemented as part of go-spacemesh.
We need a specification of these hardcoded templates.

**Comment by selfdual-brain** [comment]
Spec: 
https://docs.google.com/document/d/1vrnhRgWgcurDTG-RsG-97Mm4pcu4osUe6dOyFcuismg/edit

**Comment by lrettig** [comment]
this has already been implemented
