### ISSUE TITLE
Redundant PoET registration

### ISSUE THREAD

**Issue by selfdual-brain** [spacemeshos/pm#181]
PoET servers are a potential single-point-of-failure. There are many scenarios where PoETs can be attacked and possibly fail. We want to establish the PoET <-> Node interface in such a way that a Node can register with multiple PoET servers.

**Comment by selfdual-brain** [comment]
Spec: https://community.spacemesh.io/t/redundant-poet-registration/310

**Comment by poszu** [comment]
Closing as already implemented in https://github.com/spacemeshos/go-spacemesh/issues/3460.
