### ISSUE TITLE
Hare 2.0 dev-level specification

### ISSUE THREAD

**Issue by selfdual-brain** [spacemeshos/pm#182]
Hare protocol as described in the math paper is not suitable for the purpose of implementation checking - this is due to rather big gap between mathematical notation and standards vs software engineering reality. For the needs of development, a dev-friendly specification of the protocol must be created. This specification will then become part of the official Spacemesh protocol spec (to be published on our website).

The following side-effects of this effort are expected:

- discrepancies between current implementation and protocol definition to be identified/clarified/fixed
- possible glitches and missing details in the math description of Hare to be identified
- Hare protocol is to be brute-force tested via simulation, this including:
      1. explicit attacks to the protocol
      2. running the protocol over unreliable network

**Comment by selfdual-brain** [comment]
As of Nov 23rd 2022 this is still work in progress. Achieved so far:

- round-base simulator is implemented
- notify-msg counting problem found (recognized as implementation bug)
- eligibility calculation “potential problem” found - checking in progress
- equivocation attacks (especially the pre-round equivocation attacks) better understood
- locking of protocol in presence of lost messages found; mitigation found and tested in the simulator
- extensive brute-force testing of consensus consistency (but so far only in small networks)
- holes in the math proofs found:
     1. missing portion of Lemma A.5 proof
     2. active nodes randomization inconsistent with f+1 honest nodes assumption
- general problems with the math paper found:
     1. SVP formation description has missing cases
     2. math conventions are not followed (for example it uses “updating of variables”)
     3. inconsistent notation and conflicting types
     4. faulty-nodes model not mapping well to engineering model (because on the engineering side faultiness of nodes and faultiness network are fundamentally separated)

On going work:
 
- change in notify counting got specified
- equivocations defense specification is under-construction
- eligibility calculation (small networks case) is undergoing review

Future work:

- Simulation:
    1. implement new version of the sim (with gossip and DES)
    2. implement various attack scenarios (mostly equivocation-based attacks)
    3. execute several experiments (with attacks) and measure protocol efficiency
- Review of new Hare proofs as soon as research team have them ready (really this should be a rewrite of the whole appendix)
- Write the final dev-spec of Hare (to be published online by the end of January 2023)
- Prepare the simulation numerical results (stats/graph on the results got from the simulation)

**Comment by lrettig** [comment]
no pending work here. we'll better document hare as part of protocol documentation effort.
