### ISSUE TITLE
Calculate+simulate Hare bandwidth requirements

### ISSUE THREAD

**Issue by selfdual-brain** [spacemeshos/pm#193]
We need to understand the size of data that must be transmitted while running Hare protocol. There are 3 levels of this:
- theoretical calculation "on paper"
- measurements in the simulator
- measurements in test network (with production code).

In particular we would like to understand how the upload/download values are going to change on network growth and which portion of this is the gossip overhead.

**Comment by selfdual-brain** [comment]
Relevant effort at dev side is tracked here: https://github.com/spacemeshos/go-spacemesh/pull/3798

**Comment by selfdual-brain** [comment]
https://community.spacemesh.io/t/hare-data-volume-optimizaton/330

**Comment by lrettig** [comment]
to be handled as part of hare3 rollout
