### ISSUE TITLE
SVM management of global state

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#2]
https://github.com/spacemeshos/svm/issues/212

Discussed in R&D meeting 2021/02/09

**Comment by moshababo** [comment]
2021/02/09 R&D call takes:
* Templates should be considered as immutable objects and part of the global state tree. The actual binary code should be stored under SVM. 
* Smart contracts storage should be part of the global state tree, as discussed previously.
* We should proceed with the current Ethereum’s Merkle Trie for the global state tree implementation. The final canonical representation of the tree depends on the validators protocol, which isn’t ready yet.

**Comment by moshababo** [comment]
2021/02/09 R&D call agreements:

* Templates should be considered as immutable objects and part of the global state tree. The actual binary code should be stored under SVM. 
* Smart contracts storage should be part of the global state tree, as discussed previously.
* We should proceed with the current Ethereum’s Merkle Trie for the global state tree implementation. The final canonical representation of the tree depends on the validators protocol, which isn’t ready yet.
