### ISSUE TITLE
Evaluate POPS-VRF scheme using PoW to find a nonce

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/pm#200]
With the finalisation of https://github.com/spacemeshos/pm/issues/195 a POPS-VRF is implemented to avoid adversaries to grind keys for an advantage in some parts of the protocol.

There are ideas to improve on this scheme that can be found on Slack and the research forum. We should evaluate those ideas and if agreed to be attainable further specify and implement them.

See also
- https://spacemesh.slack.com/archives/CG91F13C7/p1670030522005729
- https://spacemesh.slack.com/archives/CG91F13C7/p1670279590565679
- https://spacemesh.slack.com/archives/CG91F13C7/p1667841308041049
- https://community.spacemesh.io/t/tree-free-post-in-more-depth/53/50
- https://community.spacemesh.io/t/tree-free-post-in-more-depth/53/28

**Comment by lrettig** [comment]
@fasmat is there anything remaining to be done here?

**Comment by fasmat** [comment]
I don't think so, since the last update to this ticket (Dec 7, 2022) the POPS-VRF scheme hasn't been changed, therefore I'll close this ticket.
