### ISSUE TITLE
Protocol: Allow Smeshers to change identity size

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/pm#209]
### Description

With https://github.com/spacemeshos/go-spacemesh/issues/3759 nodes refuse to accept incoming ATXs where the identity behind them claims to have increased their PoST size, because this would in many cases require nodes to also publish a new POPS-VRF nonce that satisfied the increased difficulty that comes from having a larger PoST.

This issue is based on comments from https://github.com/spacemeshos/go-spacemesh/issues/3773 and outlines the changes necessary to allow Smeshers to increase their PoST again.

### Acceptance criteria

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3759
  - temporary disable PoST space increases until the protocol changes are in place that allow to verify it correctly
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3902
  - cleanup the design of VRF signer and verifier implementation
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3962
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3963

#### After Genesis

- [x] https://github.com/spacemeshos/post/issues/90
  - Update VRF Nonce finding to search for the best nonce (lowest value) instead of the first that satisfies the threshold. This allows smeshers to increase their PoST size without having to search the previously calculated labels again for a value that satisfies the difficulty.
- [x] A smesher should be able and increase the disk space allocated for their PoST, ideally with minimal to no downtime.
  - This possibly requires a dedicated cmdline tool or additional GRPC calls and UI designs.
- [x] With all tickets closed above this ticket can also be closed: https://github.com/spacemeshos/go-spacemesh/issues/3773

#### After Genesis

- The local post metadata might need to be updated to include information of which range of labels is corrupted / missing.

**Comment by fasmat** [comment]
Tagging @pigmej, @lrettig, @countvonzero and @noamnelke for review.

@noamnelke: I don't see the need for an `EffectiveNumUnits` value if we just use `NumUnits` value that is valid for the given identity in the given epoch. Just like an updated `VRFNonce` it would become valid in the epoch after the ATX was published.

@pigmej I will split up this ticket into multiple (one or two per repo) after I have some feedback here. I will also split them up into a pre- and post-genesis issue if applicable.

**Comment by noamnelke** [comment]
Response to
> The changed numUnits value becomes effective in the epoch after the ATX was published, just like the updated VRF.

and

> @noamnelke: I don't see the need for an `EffectiveNumUnits` value if we just use `NumUnits` value that is valid for the given identity in the given epoch. Just like an updated `VRFNonce` it would become valid in the epoch after the ATX was published.

No... The way our proof of allocated resource works is that you prove you had the data before and after PoET (by committing the PoST proof before to PoET and using the PoET proof as a challenge to another PoST proof). This means that when a smesher changes the number of units that they prove between before and after, there's actually only a proof for the lower of the two numbers.

This means that when space increases, it only takes effect for the next ATX (so not the next epoch, but the one after).

Effectively, we should just use the lower value between the previous ATX `NumUnits` and this ATX's value.

> **after Genesis:** When reading from disk to build a PoST proof a node must be able to detect a disk failure and be able to skip the corrupted / missing data.

I think this should be done **before genesis**. I find it very brittle if a single bad sector on a disk will cause smeshers to lose their entire eligibility, with no simple way to recover. This could actually be a security concern, as some portion of honest smeshers are expected to experience this at any given epoch and thus the attacker gets an advantage (assuming they can modify their own code to ignore such failures).

This should also be quick and easy to do, imo.

**Comment by fasmat** [comment]
Smeshers can change their identity size already. To achieve this they have to shut down the node, increase the post size with `postcli` and start the node again.

To minimize down time they can use `postcli` to generate the additional `postdata_XX.bin` files in a different location and only shut down the node when moving the new files into the post data directory and then start the node again.

**Comment by tjb-altf4** [comment]
> Smeshers can change their identity size already. To achieve this they have to shut down the node, increase the post size with `postcli` and start the node again.
> 
> To minimize down time they can use `postcli` to generate the additional `postdata_XX.bin` files in a different location and only shut down the node when moving the new files into the post data directory and then start the node again.

The process you describe is undocumented and the ability to grow or shrink never actually announced as possible... can this be addressed?
Even if software allows it, this has been proven to not be enough guarantee as to not be seen as malicious, and then be subsequently slashed/banned from the network.

**Comment by pigmej** [comment]
We will work on providing some official guides for shrinking/growing the storage space.

> Even if software allows it, this has been proven to not be enough guarantee as to not be seen as malicious, and then be subsequently slashed/banned from the network.

The work in that issue was about protocol support. The software support for that is a bit sparse.
