### ISSUE TITLE
Adjust POST algorithm to the latest agreements

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#217]
We need to adjust POST algorithm to the recent agreements:
* `K2=8000`
* `K3=50`

`K3` is the subset of `K2` that is used to validate the proof. We need to make sure that each node will always validate the same `K3` indices from given K2 indices. We should use Fisher-Yates shuffle.

Besides that we should increase the bits per label to `16` so also we need to change `N` to script to `8192`.

**Comment by fasmat** [comment]
Fisher-Yates needs a source of randomness, ~~we should use Mersenne twister (or another well known PRNG) with the set of indices as seed~~ we will use blake3. Here is some pseudo code on how to implement our shuffling algorithm:

```
-- the set containing K2 valid indices below difficulty
a ← [i_1 ... i_k2] 
seed ← encode a as sequence of little endian uint64 integers

-- use the seed as pre-image for blake and read a 100 byte digest
b <- Blake::new(seed)
digest <- b.digest(100)

-- To shuffle an array a of n elements (indices 0..n-1):
for i from 0 to k3-1 do
     -- random integer such that i ≤ j < k2
     j ← (int16(digest[2*i : 2*i + 1]) mod k2-i) + i 
     exchange a[i] and a[j]

-- the set containing the random subset k3 that is validated
b ← a[0:k3-1]
```
