### ISSUE TITLE
Stable testnet

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#236]
Stable testnet means:
* no problems detected in 10 days
* transactions, sync, security all is ok.
* poet works smoothly for 10 days straight and multiple rounds are executed.

**Comment by pigmej** [comment]
The remaining item int testnet-04 is working smapp

**Comment by pigmej** [comment]
Testnet-04 had problems. Sadly that network cannot be announced to the community.

The current plan assumes having testnet-05 early next week, and having one short lived devnet from today over the weekend.

**Comment by lrettig** [comment]
Testnet-05 is stable so far after three weeks.
