### ISSUE TITLE
Set up initial PoET servers

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#238]
This is the initial set of production-grade, bare metal PoET servers that will serve the network.

- [x] poet 10
   - [x] experiment with the setup and prepare the hardware list
   - [x] finalize assembly
   - [x] install OS
   - [x] ship to DC
   - [x] configure firewall and ddos protection
- [x] poet 11
   - [x] finalize assembly
   - [x] install OS
   - [x] ship to DC
   - [x] configure firewall and ddos protection
- [x] poet 12
   - [x] finalize assembly
   - [x] install OS
   - [x] ship to DC
   - [x] configure firewall and ddos protection

**Comment by pigmej** [comment]
We're facing some hardware problems with poet-12, first motherboard fried, now seems that we have issue with the memory sticks.
