### ISSUE TITLE
Smapp 0.2

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#24]
- [ ] Use API 2.0 and SM Webs Services
- [ ] Implement new flows: https://product.spacemesh.io/resources/wallets_usage_flows.png
- [ ] Wallet-only mode with public API and no local node
- [ ] Fully integrate Smesher API and gpu-var-post flow.
- [ ] New screens: smesher, network, dashboard.

**Comment by lrettig** [comment]
designed and implemented
