### ISSUE TITLE
Finalize and announce genesis ceremony

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#241]
Announce when and how the "genesis ceremony" will work. For example:

Wait for the Bitcoin block at height X (expected on or around Y future date/time). Once block X+6 is produced, around an hour later, we take the 32 byte hash of block X and announce this as the official, final "golden ATX" value. We'll then generate a genesis config file containing this value and a genesis time Z in the future and release this publicly on [Github, Twitter, Discord, etc.]. Once this has been published, smeshers can use it to begin initializing their storage space for mainnet.

Target announcement date: 2023/06/30

**Comment by pigmej** [comment]
https://github.com/spacemeshos/wiki/wiki/Genesis-ceremony
