### ISSUE TITLE
Make discovery service aware of platform, versions etc.

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#244]
Because sometimes we may need to ship different node-config based on the platform / version where the node is running on we need to extend the discovery service.

- [x] https://github.com/spacemeshos/smapp/issues/1297
- [x] Discovery service should be ready on the infrastructure side to handle that and serve different content based on needs and query string

**Comment by lrettig** [comment]
@pigmej why not put this logic into smapp? i.e., let it download all the metadata and sort it out locally.

**Comment by pigmej** [comment]
1) based on that we can have dynamically adjusted config on our end
2) we get the per os downloads "for free" so we can act accordingly
3) we don't have to maintain too much logic on smapp side
4) especially later on we could serve different configs based on whatever we need in given moment WITHOUT needing to update logic on smapp side.

That is meant to work only in case when let's say M1 apple silicon is having issues and needs config change etc. Nothing permanent, nothing "true metadata".
