### ISSUE TITLE
Variable Size PoST

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#25]
Research forum thread: https://community.spacemesh.io/t/weights-and-measures-for-blocks-and-hare-rounds/58
SMIP: https://github.com/spacemeshos/SMIPS/issues/6

- [x] Initial implementation (allow heterogeneous PoST size, consider miner weight in block and Hare eligibility oracle, weighted Hare messages). PR: https://github.com/spacemeshos/go-spacemesh/pull/2039
- [ ] Calculate and tune the supported PoST granularity and scale (in what units is space defined, what's the min/max per node, ensure we support any feasible amount of total storage and/or handle the case where we exceed the expected total storage).
- [ ] Support changing the miner's space dedicated to PoST after the first ATX (at the protocol- and node-level).
- [ ] PoET ticks.
- [ ] Block weight. Miner weight changes the number of eligible blocks, so all have _roughly_ the same weight. The remainder should be accounted for when counting votes and distributing rewards.
- [ ] Consolidate blocks in the same layer from the same miner (sum of the weight, more loose transaction limits - same count, but higher total weight/gas of transactions).

**Comment by lrettig** [comment]
@noamnelke could you please review outstanding tasks here and close this if they're done?

**Comment by lrettig** [comment]
designed and implemented
