### ISSUE TITLE
Change the p2p discovery

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#251]
The idea would be to switch to in-house libp2p discovery. Our custom implementation is not worth the hassle, it would require way too much maintenance and adjustments to support more protocols like quic etc.

Therefore let's switch to the in-house libp2p discovery implementation.

**Comment by robandfender** [comment]
This caused the stability of ver1.0.9 to be relatively weak, and smapp would disconnect once a day, even if I turned on the UPNP setting in the physical router

**Comment by pigmej** [comment]
It was addressed by https://github.com/spacemeshos/go-spacemesh/pull/4736
