### ISSUE TITLE
New PoST

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#26]
- [x] `gpu-post` lib base functionality
- [x] `gpu-post` lib test suite
- [x] `gpu-post` lib to support variable output size up to 32 bytes 
- [ ] `gpu-post` lib to support blake3
- [x] Tree-less proving
- [x] Smesher API Service implementation
- [ ] `go-spacemesh` integration

SMIPs: https://github.com/spacemeshos/SMIPS/issues/14, https://github.com/spacemeshos/SMIPS/issues/27

**Comment by avive** [comment]
blake3? I'm not aware that we decided to do this over the current gpu-post implementation. It is a non-trivial project if it means doing blake3 in gpu-compute.

**Comment by lrettig** [comment]
designed and implemented
