### ISSUE TITLE
Self Healing

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#27]
Research forum threads: [Effficient Vote Encoding: Encoding checkpoints for efficient tortoise verification](https://community.spacemesh.io/t/effficient-vote-encoding-encoding-checkpoints-for-efficient-tortoise-verification/72/3), [Formally Defining Self-Healing](https://community.spacemesh.io/t/formally-defining-self-healing/76)
SMIP: https://github.com/spacemeshos/SMIPS/issues/46

Implementation: https://github.com/spacemeshos/go-spacemesh/pull/2400
See also: https://github.com/spacemeshos/go-spacemesh/labels/self-healing

**Comment by lrettig** [comment]
This is done. Followup items in #80.
