### ISSUE TITLE
api v2

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/pm#270]
this is placeholder issue to hold API improvements

v2alpha1 api specification based on Lane and Kirill requirements:
* Requirements: https://github.com/spacemeshos/api/issues/295
* Schema: https://github.com/spacemeshos/api/pull/300

### API services
- [x] account service
- [x] activation service
- [ ] block service
- [x] layer service
- [x] network service
- [x] node service
- [x] reward service
- [x] tx service

Every service will contain Stream (private grpc) and List (public grpc - with pagination) endpoints to have minimal safe API.

---

the goal is to have efficient (in terms of cpu and disk usage) and correct (atleast once delivery semantics with reorg support) client to facilitate:
- data indexing for explorer
- full data observability

the implementation will consist of streams per every object (atxs, ballots, blocks, txs, tx results, reward, certificates, proposals). every object will be complete, in a sense that it should be possible to re-encode it in scale and verify signatures.

every stream will read history from database and switch to inmemory subscriptions in a "correct" way. the correct way will be elaborated in technical specification. good example of such API is [stream for transaction results](https://github.com/spacemeshos/go-spacemesh/blob/develop/api/grpcserver/transaction_service.go#L302)

the competing idea is https://github.com/spacemeshos/pm/issues/269

- [ ] safe API to use in wallet-only mode

the goal is to have minimal safe API  for interacting with vm. as such it should support:
- submit transaction with strict validation (only 1 concurrent tx). this is different from sending to your own node
- poll result of the transaction and state in mempool
- query single account balance
- builtin per-ip rate limiting

- [ ] rosetta integration

https://www.rosetta-api.org/

as stated integration for rosetta API

--- 

from that list 1 and 2 items have a higher priority and can be completed with 1-2 month, rossetta can be completed later within 6 month.

**Comment by pigmej** [comment]
> builtin per-ip rate limiting

That's something that IMO is better to do on LB level.

**Comment by pigmej** [comment]
The progress is reported: https://github.com/spacemeshos/api/issues/295#issuecomment-2032459220

**Comment by pigmej** [comment]
The last "missing" item here was the rosetta integration. We have decided to skip it for now. The rest is done.
