### ISSUE TITLE
decentralize p2p network

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/pm#275]
the problem with existing setup is that many nodes are undialable and therefore spacemesh has to run CDN-like nodes (that we call boosters internally) that help with network connectivity.

this is not good for network long term health and we want to fix it when time allows. in the past we failed with libp2p hole punching protocol, but it could be due to rushing things. we want to:
- enable quic / webrtc transport
- retest hole punching protocol
- measure it

this doesn't introduce any immediate issues, but not good for network health long term

**Comment by ivan4th** [comment]
With P2P decentralization (#[5329](https://github.com/spacemeshos/go-spacemesh/pull/5329)) and fetch streaming (#[5562](https://github.com/spacemeshos/go-spacemesh/pull/5562)) merged, we're currently trying to enable decentralization features in the network. The current problem appears that the routing discovery mechanism causes too much network load on the user nodes.

The following items are planned:
* https://github.com/spacemeshos/go-spacemesh/pull/5815: increase and randomize routing discovery advertisement interval
* enable QUIC on the network (better hole-punching efficiency)
* slow down routing discovery mechanism

**Comment by ivan4th** [comment]
Testing QUIC on the testnet. There was an issue with malfeasance sync on testnet, fixed: spacemeshos/go-spacemesh#5851

Looking into reports that streaming mode is somehow causing too many TCP connections (?)

**Comment by ivan4th** [comment]
spacemeshos/go-spacemesh#5792 should facilitate diagnostics of possible network issues after we try to enable decentralization next time. It would be best to include corresponding views in SMAPP.

spacemeshos/go-spacemesh#5882 should reduce network strain due to DHT and connection activity after routing discovery is enabled

**Comment by ivan4th** [comment]
spacemeshos/go-spacemesh#5902 adds QUIC mode systests

**Comment by pigmej** [comment]
This is done, the default smapp setup now includes quic and discovery enabled. Improvements will come in separate tasks.
