### ISSUE TITLE
New Sync

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#30]
SMIP: https://github.com/spacemeshos/SMIPS/issues/24
PR: https://github.com/spacemeshos/go-spacemesh/pull/2213

- [x] write fetch hash infrastructure
- [x] refactor ands consolidate message receivers for more generic approach to handling incoming data
- [x] consolidate sync / gossip paths
- [x] write unit tests for fetch
- [x] run long term run of fetch mechanism
- [x] integrate sync fetch infra into node
- [x] write sync new logic
- [ ] design new is synced indication
- [ ] implement new is synced indication
- [ ] implement missing sync in hare
- [ ] test new sync flow

**Comment by lrettig** [comment]
designed and implemented
