### ISSUE TITLE
Distributed verification

### ISSUE THREAD

**Issue by mathcrypto** [spacemeshos/pm#308]
See [#5185](https://github.com/spacemeshos/go-spacemesh/issues/5185)

https://community.spacemesh.io/t/non-trivial-improvements-to-post-ux-and-large-atx-incentivization/377/5

**Comment by dshulyak** [comment]
i think there is already item for this in go-spacemesh repo

**Comment by mathcrypto** [comment]
Thank you for referring it. I'll delete this one to avoid repetition
