### ISSUE TITLE
Transaction Processing

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#32]
- [ ] Fully [Integrate go-svm](https://github.com/spacemeshos/SMIPS/issues/20)
- [ ] Implement support all 6 transaction types [per smip](https://github.com/spacemeshos/SMIPS/issues/23)
- [ ] Add net-id to transactions sign and verify algorithms
- [ ] Generate receipts
- [ ] Handle svm exceptions properly - gas and receipts

**Comment by lrettig** [comment]
all implemented (except receipts, that's still a to do, tracked separately)
