### ISSUE TITLE
API Refactoring

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#35]
SMIP: https://github.com/spacemeshos/SMIPS/issues/21
Epic: https://github.com/spacemeshos/go-spacemesh/issues/1764
Board: https://github.com/orgs/spacemeshos/projects/11

**Comment by avive** [comment]
Isn't this done for 0.2? @lrettig @moshababo

**Comment by lrettig** [comment]
I'm not aware of any pending API changes for 0.2 other than @moshababo's work on post init. Also @AmitShaul needs some things added for systests but I'm not sure that's on the critical path for 0.2.

**Comment by avive** [comment]
There's a PR for @moshababo work on POST and Amit's work should only affect the Debugging service which is not really used in the 0.2 products so I think you can close this issue.

**Comment by lrettig** [comment]
All the high level work has been done. There are issues to track remaining followup work such as documentation and optimization.
