### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#36]
Evaluate [backlog tasks](https://github.com/spacemeshos/go-spacemesh/labels/log)

**Comment by avive** [comment]
Regarding logging, it will be great if the logs growth rate is greatly reduce for home smeshers. It is currently reaches 1GB of logs for a 6 days old network. That's ~170MB per 24 hours. Can the log-level for home-smesher be set so it only logs things that went wrong (errors / warnings) and not thing that work as expected (info)? @moshababo @lrettig

**Comment by lrettig** [comment]
nothing remaining to be done here
