### ISSUE TITLE
Spacemesh node analytics

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#37]
SMIP: https://github.com/spacemeshos/SMIPS/issues/10
- [x] Deploy base prometheus/grafana stack
- [x] Configure metrics gathering from spacecraft nodes
- [x] Implement metrics push 
- [x] Arrange metrics in node
- [x] Deploy final version of prometheus/grafana stack
- [x] Write a proxy to get metrics from community nodes

**Comment by avive** [comment]
Can we please add to the following task:
Collect public ip addresses from each node connection to the proxy, geo-decode them and store (ip, lat/long, smesher id, last_seen) in store + expose api to get all this data? We need this for the heat map and dash (long overdue feature). Not sure if this is a metrics or a telemetry. @moshababo

**Comment by avive** [comment]
I still don't fully understand the difference between metrics and telemetry and how metrics are related to the work Alex has done for node telemetry (if at all).

**Comment by lrettig** [comment]
this is done
