### ISSUE TITLE
Spacecraft Monitoring

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#38]
The aim is to add protocol and infrastructure resources monitoring to spacecraft. 

The VMs resource utilisation can be monitored using GCP monitoring suite. For monitoring protocol features we have developed a Spacemesh Watch (https://github.com/spacemeshos/spacemesh-watch) microservice which takes a set of node API endpoints and monitors constantly and for assertions it triggers alerts on slack. The idea behind creating a separate microservice for monitoring is that we can use it with any sort of network i.e., spacecraft, local testnet or any other future tools or services.
 
- [x] Setup GCP monitoring for CPU and Memory usage of VMs
- [x] Monitor progress of verified layers: After every constant interval of time check if the verified layer has incremented. The interval by default is 1 hour but is configurable on the fly using CLI options.
- [x] Monitor if any node is down and/or API service cannot be reached
- [x] Integrate Slack for Notifications
- [x] Prevent duplicate error notifications on slack. For example: If a miner fails a notification will be send. But when checked again if it's still down then don't send notification again thus preventing spamming of slack channel.
- [ ] Monitor usual number of blocks per layer/epoch
- [ ] Execute transactions and ensure that they work and change state for each node
- [ ] Monitor Mempool size and check if transactions haven’t cleared for 5 consecutive layers
- [ ] Sync result and time to sync new node. Also add new nodes dynamically to test
- [ ] Transaction broadcasting time to every node - E.g. send a transaction every minute, from a random managed miner and measure when each one of the other managed miners reports receiving it. Then ensure that/when all those transactions are mined and applied to the global state.
- [ ] Monitor at what round Hare consensus is achieved
- [ ] Measure total weight of the hare messages per round
- [ ] Measure and record total number of ATXs published in the last epoch. 
- [ ] Dockerise the service
- [x] Node status syncing but synced layer not incrementing
- [x] If all nodes have same global state root hash for the same verified layer
- [ ] Monitor Poet servers
- [ ] Show Miner ID/Name instead of IP:PORT

**Comment by lrettig** [comment]
Is this still relevant?

**Comment by web3rover** [comment]
We can close this.
