### ISSUE TITLE
Spacecraft improvements

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#39]
Looking at the current limitations of spacecraft and issues we faced recently in terms of security and upgradability of spacecraft these improvement are suggested.

- [x] Create and Deploy network on kubernetes
- [x] Adding miners to the network (ability to provide different configuration)
- [x] Delete miners from the network
- [x] Upgrade the release version of the miners
- [x] Create a network which joins another network i.e., without bootstrap node
- [ ] Integrator GCP Accelerators and test n1-standard-2 GC instances, with 4 Tesla T4 GPUs
- [x] Test a network with 1000 miners
- [x] Setup ELK on k8s
- [ ] Alerts on slack for miner/poet/elk containers CPU & Memory spikes and Disk Usage
- [x] Convert all fields in logs to strings and don't parse non-JSON logs instead store them raw
- [ ] Setup Prometheus and Grafana
- [x] Logs lifecycle management
- [x] Auth, Domain name and SSL for Kibana
- [x] Calculate Rewards
- [x] Generate different coinbase for each miner and store key in k8s secret
- [x] List API URLs of miners
- [ ] Delete volumes when deleting cluster

**Comment by lrettig** [comment]
Closing as we're no longer maintaining spacecraft
