### ISSUE TITLE
Transaction Syntax / Encoding

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#43]
- https://github.com/spacemeshos/SMIPS/issues/12
- https://github.com/spacemeshos/SMIPS/issues/23
- https://github.com/spacemeshos/SMIPS/issues/76
- https://github.com/spacemeshos/SMIPS/issues/77

see also #65

**Comment by selfdual-brain** [comment]
The spec is here: 
https://docs.google.com/document/d/1QSBsBdDvB3zc0J8jJgN5Y4iv9T5HDcD0QONsQbig5Po/edit#

The work is continued here (with somewhat bigger scope):
https://github.com/spacemeshos/pm/issues/176

**Comment by lrettig** [comment]
this is done
