### ISSUE TITLE
Read Spacemesh Documentation

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/pm#59]
https://github.com/spacemeshos/protocol
https://spacemesh.io/overview/?page=mesh

**Comment by avive** [comment]
Better rendering of protocol docs here: https://platform.spacemesh.io/docs/protocol/overview

**Comment by dshulyak** [comment]
I am going to close it. I will be definitely reading more in the background when I will work on various issues. But I don't need a dedicated task for that.
