### ISSUE TITLE
Create dev tasks breakdown for Account Unification

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#64]
https://github.com/spacemeshos/SMIPS/issues/49

**Comment by YaronWittenstein** [comment]
The issues & SMIPs created for the `AA` & Integration with `go-svm` are here:

## Issues

#### **AA** label

https://github.com/spacemeshos/svm/issues?q=label%3AAA

#### **go-svm** label

https://github.com/spacemeshos/svm/issues?q=label%3Ago-svm


## SMIPs

https://github.com/spacemeshos/SMIPS/issues/53

**Comment by lrettig** [comment]
all done
