### ISSUE TITLE
Groom tasks from research

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/pm#71]
## Description
check status of following research topics to start planning long term team strategy:

- [ ] Transactions selection
- [ ] New transactions syntax
- [ ] SVM integration
- [ ] Vaults
- [ ] Account Abstraction
- [ ] Global state integration
- [ ] Inflation/issuance scheme
- [ ] Rewards and incentives scheme
- [ ] GPU-PoW

**Comment by avive** [comment]
gpu-pow status: implementation is done and the functionality has shipped in the latest github library release. The lib needs a comprehensive review from research team for 0.3 and beyond.

**Comment by lrettig** [comment]
This board is reasonably up to date. Happy to provide more info as needed! https://github.com/orgs/spacemeshos/projects/18

**Comment by lrettig** [comment]
Nothing pending here, the latest is in the linked project board and #92
