### ISSUE TITLE
Self-healing follow up items

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#80]
Roughly in order of priority:

Critical:

- [x] https://github.com/spacemeshos/go-spacemesh/issues/2687
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2692
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2677
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2629
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2540
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2679
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2719
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2424
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2688
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2522

Medium priority/nice to have:

- [x] https://github.com/spacemeshos/go-spacemesh/issues/2672 (also related: https://github.com/spacemeshos/go-spacemesh/issues/2675, https://github.com/spacemeshos/go-spacemesh/issues/2676)
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2680
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2671
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2497
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2369
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2402
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2707
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2674
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2678
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2673
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2428

Some bigger, architectural stuff that needs more thought and design:

- [x] https://github.com/spacemeshos/go-spacemesh/issues/2552
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2551
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2412
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2415

Others:
- https://github.com/spacemeshos/go-spacemesh/issues?q=is%3Aopen+label%3A%22Tortoise+Protocol%22%2Chealing
- https://github.com/spacemeshos/go-spacemesh/issues/2924

**Comment by dshulyak** [comment]
I am closing this epic. There are several important things that are tracked in here, but they are can be tracked as a standalone issues.
