### ISSUE TITLE
Add a changelog and release notes to go-sm

### ISSUE THREAD

**Issue by daonb** [spacemeshos/pm#83]
> A changelog is a file which contains a curated, chronologically ordered list of notable changes for each version of a project.
> https://keepachangelog.com/

To better track the node's history we will ad a CHANGELOG.md file to the the root of the go-spacemesh repo.  In addition to the changelog we there are optional version release notes under `docs/notes`

- [ ] add change log instructions to `CONTRIBUITING.md"
- [ ] Write a guide explaining to a first-time release manager what's he needs to do and what happens in the background.
The doc should carry a TBD headline and serve for to coordinate the automation efforts. Is should clearly define how to name a version and wha't considered a "Compatibility Breaking Change". This will require upgrading the PR template to allow contributors to mark compatibility breaking changes.
- [ ] When the user tags a version in the form of `v<SemVer>` a gh workflow should kick in to build a zip file for each supported platform and publish it on gh's release page. The zip file should include a README.md, a LICENSE file, go-sm's CHANGELOG and the binaties includes in the version. The version's description should be copied either from a release note (if there is one) or from the version's section in CHANGELOG.md. depends on https://github.com/spacemeshos/go-spacemesh/pull/2762

**Comment by lrettig** [comment]
all done
