### ISSUE TITLE
Optimized self-healing

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#93]
See:

- [ ] https://github.com/spacemeshos/go-spacemesh/issues/2522 (better algorithm/checkpointing for recovering from self-healing)
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/2679 (optimize tortoise data structure and self-healing algorithm)

Per Tal, these are both essential for genesis.

See also: #80

**Comment by dshulyak** [comment]
not relevant
